# Deployment Device
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf1-dev1
spec:
  selector:
    matchLabels:
      app: sdci-gwf1-dev1
  replicas: 4
  template:
    metadata:
      labels:
        app: sdci-gwf1-dev1
    spec:
      containers:
      - name: sdci-gwf1-dev1-container
        image: sdci-device:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 9001
        env:
          - name: LOCAL_IP
            value: "sdci-gwf1-dev1-clusterip"
          - name: LOCAL_PORT
            value: "9001"
          - name: LOCAL_NAME
            value: "gwf1-dev1"
          - name: REMOTE_IP
            value: "sdci-gwf1-clusterip"
          - name: REMOTE_PORT
            value: "8282"
          - name: REMOTE_NAME
            value: "gwf1"
          - name: SEND_PERIOD
            value: "2000"
