# Deployment Device
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf2-dev2
spec:
  selector:
    matchLabels:
      app: sdci-gwf2-dev2
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwf2-dev2
    spec:
      containers:
      - name: sdci-gwf2-dev2-container
        image: sdci-device:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 9012
        env:
          - name: LOCAL_IP
            value: "sdci-gwf2-dev2-clusterip"
          - name: LOCAL_PORT
            value: "9012"
          - name: LOCAL_NAME
            value: "gwf2-dev2"
          - name: REMOTE_IP
            value: "sdci-gwf2-clusterip"
          - name: REMOTE_PORT
            value: "8383"
          - name: REMOTE_NAME
            value: "gwf2"
          - name: SEND_PERIOD
            value: "3000"
