# Service ClusterIP for Device
apiVersion: v1
kind: Service
metadata:
  name: sdci-gwf2-dev1-clusterip
spec:
  selector:
    app: sdci-gwf2-dev1
  ports:
  - protocol: TCP
    name: http    
    port: 9011
    targetPort: 9011
  type: ClusterIP