# Deployment Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-application
spec:
  selector:
    matchLabels:
      app: sdci-application
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-application
    spec:
      containers:
      - name: sdci-application-container
        image: sdci-application:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 7001
        env:
          - name: REMOTE_IP
            value: "sdci-server-clusterip"
          - name: REMOTE_PORT
            value: "8080"
          - name: DEVICE_NAME
            value: "dev1"
          - name: SEND_PERIOD
            value: "5000"