# Deployment Device
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-device
spec:
  selector:
    matchLabels:
      app: sdci-device
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-device
    spec:
      containers:
      - name: sdci-device-container
        image: sdci-device:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 9001
        env:
          - name: LOCAL_IP
            value: "sdci-device-clusterip"
          - name: LOCAL_PORT
            value: "9001"
          - name: LOCAL_NAME
            value: "dev1"
          - name: REMOTE_IP
            value: "sdci-gateway-finale1-clusterip"
          - name: REMOTE_PORT
            value: "8282"
          - name: REMOTE_NAME
            value: "gwf1"
          - name: SEND_PERIOD
            value: "3000"
