# Deployment Gateway i
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwi
spec:
  selector:
    matchLabels:
      app: sdci-gwi
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwi
    spec:
      containers:
      - name: sdci-gwi-container
        image: sdci-gateway:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8181
        env:
        - name: LOCAL_IP
          value: "sdci-gwi-clusterip"
        - name: LOCAL_PORT
          value: "8181"
        - name: LOCAL_NAME  
          value: "gwi"
        - name: REMOTE_IP
          value: "sdci-srv-clusterip"
        - name: REMOTE_PORT
          value: "7777"
        - name: REMOTE_NAME
          value: "srv"
        - name: RATE
          value: "2"
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1"
