# Service ClusterIP for Application
apiVersion: v1
kind: Service
metadata:
  name: sdci-app1-clusterip
spec:
  selector:
    app: sdci-app1
  ports:
  - protocol: TCP
    name: http    
    port: 7001
    targetPort: 7001
  type: ClusterIP