# Service ClusterIP for Application
apiVersion: v1
kind: Service
metadata:
  name: sdci-app2-clusterip
spec:
  selector:
    app: sdci-app2
  ports:
  - protocol: TCP
    name: http    
    port: 7002
    targetPort: 7002
  type: ClusterIP