# Deployment Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-srv
spec:
  selector:
    matchLabels:
      app: sdci-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-srv
    spec:
      containers:
      - name: sdci-srv-container
        image: sdci-server:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 7777
        env:
        - name: LOCAL_IP
          value: "sdci-srv-clusterip"
        - name: LOCAL_PORT
          value: "7777"
        - name: LOCAL_NAME
          value: "srv"
