# Service ClusterIP for Server
apiVersion: v1
kind: Service
metadata:
  name: sdci-srv-clusterip
spec:
  selector:
    app: sdci-srv
  ports:
  - protocol: TCP
    name: http    
    port: 7777
    targetPort: 7777
  type: ClusterIP