# Deployment Gateway finale
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf1
spec:
  selector:
    matchLabels:
      app: sdci-gwf1
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwf1
    spec:
      containers:
      - name: sdci-gwf1-container
        image: sdci-gateway:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8282
        env:
        - name: LOCAL_IP
          value: "sdci-gwf1-clusterip"
        - name: LOCAL_PORT
          value: "8282"
        - name: LOCAL_NAME  
          value: "gwf1"
        - name: REMOTE_IP
          value: "sdci-gwi-clusterip"
        - name: REMOTE_PORT
          value: "8181"
        - name: REMOTE_NAME
          value: "gwi"