# Deployment Gateway i
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf2
spec:
  selector:
    matchLabels:
      app: sdci-gwf2
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwf2
    spec:
      containers:
      - name: sdci-gwf2-container
        image: sdci-gateway:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8383
        env:
        - name: LOCAL_IP
          value: "sdci-gwf2-clusterip"
        - name: LOCAL_PORT
          value: "8383"
        - name: LOCAL_NAME  
          value: "gwf2"
        - name: REMOTE_IP
          value: "sdci-gwi-clusterip"
        - name: REMOTE_PORT
          value: "8181"
        - name: REMOTE_NAME
          value: "gwi"
        - name: RATE
          value: "100"